const trips = [
  {
    id: 1,
    destination: "Everest Base Camp Trek",
    duration: "16 days",
    date: "from 30th Jan to 14th Feb",
    status: "Guaranteed",
    seatsLeft: 2,
    priceNow: "US$ 1525",
    priceWas: "$1601.25",
  },
  {
    id: 2,
    destination: "Langtang Valley Trek",
    duration: "10 days",
    date: "from 30th Jan to 8th Feb",
    status: "Guaranteed",
    seatsLeft: 2,
    priceNow: "US$ 750",
    priceWas: "$787.5",
  },
  {
    id: 3,
    destination: "Annapurna Panorama Trek",
    duration: "09 days",
    date: "from 30th Jan to 6th Feb",
    status: "Guaranteed",
    seatsLeft: 2,
    priceNow: "US$ 710",
    priceWas: "$745.5",
  },
  {
    id: 4,
    destination: "Ghorepani Poon Hill Family Trek",
    duration: "10 days",
    date: "from 30th Jan to 8th Feb",
    status: "Guaranteed",
    seatsLeft: 2,
    priceNow: "US$ 950",
    priceWas: "$997.5",
  },
  {
    id: 5,
    destination: "Himalayan Luxury Experience",
    duration: "08 days",
    date: "from 30th Jan to 6th Feb",
    status: "Guaranteed",
    seatsLeft: 2,
    priceNow: "US$ 2370",
    priceWas: "$2488.5",
  },
  {
    id: 6,
    destination: "Annapurna Family Hike and Nagarkot Tour",
    duration: "09 days",
    date: "from 30th Jan to 7th Feb",
    status: "Guaranteed",
    seatsLeft: 2,
    priceNow: "US$ 1525",
    priceWas: "$1601.25",
  },
];

export default trips;
