const menus = [
  {
    id: 1,
    title: "Nepal",
    submenu: [
      "Nepal Trekking",
      "Nepal Tours",
      "Day Tours",
      "Peak Climbing",
      "Helicopter Tours",
      "Short Hiking Tours",
      "Wildlife Tours",
      "Get Extra Fun",
      "Luxury Treks and Tours",
      "Photography Tours",
    ],
  },
  {
    id: 2,
    title: "Tibet",
    submenu: [
      "Lhasa - Everest Base Camp - Lhasa - 12 days",
      "Nepal Tibet Bhutan Tours - 16 days",
      "Glimpse of Tibet Tour - 5 days",
      "Lhasa to Kathmandu Tour - 8 days",
      "Saga Dawa Festival Tour - 14 days",
      "Simikot Kailash Lhasa Tour - 22 days",
      "Tibet Everest Base Camp Tour - 8 days",
      "Kathmandu and Lhasa Tour - 8 days",
      "Simikot Kailash Kerung - 19 days",
    ],
  },
  {
    id: 3,
    title: "Bhutan",
    submenu: [
      "Bhutan Highlights Tour - 6 days",
      "Western Bhutan Tour - 8 days",
      "Bhutan Tours - 4 days",
      "Glimpse of Bhutan Tour - 5 days",
      "Chomolhari Trek - 12 days",
      "Bhutan Experience Tour - 10 days",
      "Druk Path Trek - 7 days",
      "Nepal and Bhutan Tours - 10 days",
    ],
  },
  {
    id: 4,
    title: "Nepal Trekking",
    submenu: [
      "Everest Region Trek",
      "Annapurna Region Trek",
      "Langtang Region Trek",
      "Manaslu Region Trek",
      "Off the Beaten Trails",
      "Family Friendly Holidays",
      "Summer Trek Packages",
      "Winter Treks Packages",
      "Short and Easy Treks",
    ],
  },
  {
    id: 5,
    title: "Tour Packages",
    submenu: [
      "Best of Nepal Tour - 14 days",
      "Glimpse of Nepal Tours - 8 days",
      "Kathmandu Pokhara Chitwan Tour - 9 days",
      "Kathmandu Tours with Nagarkot Hike -- 5 days",
      "Glimpse of Kathmandu Tour - 4 days",
      "Kathmandu and Lumbini Tours - 5 days",
      "Kathmandu and Pokhara Luxury Tour - 5 days",
      "Culture Blends Adventure Tour - 7 days",
      "Sunrise and Sunset Tour - 7 days",
      "Discover Kathmandu and Nagarkot - 4 days",
    ],
  },
  {
    id: 6,
    title: "Travel Guide",
    submenu: [
      "Nepal Visa",
      "Equipment Checklist",
      "Nepal at a Glance",
      "Flight Cancellation",
      "Best Trekking Season",
      "Trip Grade",
      "Travel Insurance",
      "Recommended Medical Kit",
      "Recommended Flights",
      "Is Nepal Safe To Travel",
    ],
  },
  {
    id: 7,
    title: "About Us",
    submenu: [
      "Our Team",
      "Alerts",
      "Terms and Conditions",
      "How to Make a Payment",
      "How to Book a Trip with Green Nepal",
      "Privacy Policy",
      "Sustainable Tourism",
      "Legal Documents",
      "Risk free booking policy",
      "WHY green Nepal? Learn",
      "Contact Us",
    ],
  },
];

export default menus;
